sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
addons:
  apt:
    packages:
    - g++-4.9
    - gcc-4.9
    - libssl-dev
    - zlib1g-dev
    - cmake
    - redis-server
    - automake
    - libtool
    - flex
    - bison
    - pkg-config
    - libmysqlclient-dev

before_install:
    # Download boost 1.5 and extract the source archive
  - wget --no-verbose --output-document=boost_1_56_0.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost"
  - export DEBIAN_FRONTEND=noninteractive
  - mkdir -p $BOOST_ROOT
  - tar jxf boost_1_56_0.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - wget http://www.us.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz
  - export THRIFT_ROOT="$TRAVIS_BUILD_DIR/../thrift"
  - mkdir -p $THRIFT_ROOT
  - tar xf thrift-0.9.2.tar.gz --strip-components=1 -C $THRIFT_ROOT
  - wget https://cdn.mysql.com/Downloads/Connector-C++/mysql-connector-c++-1.1.6.tar.gz
  - export CONNECTOR_ROOT="$TRAVIS_BUILD_DIR/../mysql-connector-c++"
  - mkdir -p $CONNECTOR_ROOT
  - tar xf mysql-connector-c++-1.1.6.tar.gz --strip-components=1 -C $CONNECTOR_ROOT

install: 
    # Install GNU GCC 4.9 required by use of C++11
    # Build boost libraries required by ledger
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=atomic,chrono,context,coroutine,iostreams,system,test,thread)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$HOME -d0 install)
  - (cd $THRIFT_ROOT; ./configure --prefix=$HOME --with-qt4=no --with-c_glib=no --with-csharp=no --with-java=no --with-erlang=no --with-nodejs=no --with-lua=no --with-python=no --with-perl=no --with-php=no --with-php_extensioo --with-ruby=no --with-haskell=no --with-go=no --with-d=no; make -j4 install)
  - (cd $CONNECTOR_ROOT; mkdir build; cd build; cmake -DCMAKE_INSTALL_PREFIX=$HOME ..; make -j4; make -j4 install)

script: mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake -DTHRIFT_HOME=$HOME -DBOOST_ROOT=$HOME -DMYSQLCONNECTORCPP_ROOT_DIR=$HOME .. && make -j4 && ctest
